"""
sentrix_core/storage/event_store.py

Persistent SQLite store for ALL events and alerts flowing through Sentrix.
This is the primary data source for the live dashboard.

Design principles:
- One connection per call (WAL mode for safe concurrent access)
- Never blocks the Threat Engine — writes are fast inserts
- All query methods are paginated to keep API responses fast
- Deduplication by alert_id for alerts, event_hash for raw events
"""
import os
import json
import time
import sqlite3
import hashlib
import logging
import threading
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any

logger = logging.getLogger("sentrix.event_store")

_store_instance: Optional["EventStore"] = None
_store_lock = threading.Lock()


def get_event_store() -> "EventStore":
    """Module-level singleton accessor."""
    global _store_instance
    if _store_instance is None:
        with _store_lock:
            if _store_instance is None:
                from sentrix_core.config.settings import get_settings
                settings = get_settings()
                _store_instance = EventStore(db_path=settings.events_db)
    return _store_instance


class EventStore:
    """
    Unified persistent store for raw events and generated alerts.

    Tables
    ------
    raw_events   — every event ingested (Suricata, Wazuh, other)
    alerts       — every alert generated by the Threat Engine
    iocs         — extracted IOC records (IPs, hashes, domains)
    """

    def __init__(self, db_path: str = None):
        if not db_path:
            from sentrix_core.config.settings import get_settings
            db_path = get_settings().events_db

        self.db_path = db_path
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self._init_db()
        logger.info("[EventStore] Initialized at %s", self.db_path)

    # ── Connection ─────────────────────────────────────────────────────────────

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=15)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA synchronous=NORMAL")
        conn.row_factory = sqlite3.Row
        return conn

    # ── Schema ─────────────────────────────────────────────────────────────────

    def _init_db(self):
        conn = self._connect()
        try:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS raw_events (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_hash  TEXT    UNIQUE,
                    source      TEXT    NOT NULL,
                    event_type  TEXT    NOT NULL DEFAULT 'unknown',
                    src_ip      TEXT,
                    dest_ip     TEXT,
                    severity    TEXT,
                    timestamp   TEXT,
                    payload     TEXT    NOT NULL,
                    ingested_at TEXT    DEFAULT (datetime('now','utc'))
                );
                CREATE INDEX IF NOT EXISTS idx_re_source    ON raw_events(source);
                CREATE INDEX IF NOT EXISTS idx_re_src_ip    ON raw_events(src_ip);
                CREATE INDEX IF NOT EXISTS idx_re_event_type ON raw_events(event_type);
                CREATE INDEX IF NOT EXISTS idx_re_ingested  ON raw_events(ingested_at);

                CREATE TABLE IF NOT EXISTS alerts (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    alert_id     TEXT    UNIQUE,
                    rule_id      TEXT,
                    rule_name    TEXT,
                    severity     TEXT,
                    risk_score   REAL,
                    source_ip    TEXT,
                    affected_host TEXT,
                    source_type  TEXT    DEFAULT 'suricata',
                    mitre_data   TEXT,
                    suppressed   INTEGER DEFAULT 0,
                    payload      TEXT    NOT NULL,
                    created_at   TEXT    DEFAULT (datetime('now','utc'))
                );
                CREATE INDEX IF NOT EXISTS idx_al_severity  ON alerts(severity);
                CREATE INDEX IF NOT EXISTS idx_al_source_ip ON alerts(source_ip);
                CREATE INDEX IF NOT EXISTS idx_al_created   ON alerts(created_at);

                CREATE TABLE IF NOT EXISTS iocs (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    ioc_type    TEXT    NOT NULL,
                    value       TEXT    NOT NULL,
                    source_ip   TEXT,
                    alert_id    TEXT,
                    context     TEXT,
                    first_seen  TEXT    DEFAULT (datetime('now','utc')),
                    last_seen   TEXT    DEFAULT (datetime('now','utc')),
                    UNIQUE(ioc_type, value)
                );
                CREATE INDEX IF NOT EXISTS idx_ioc_type  ON iocs(ioc_type);
                CREATE INDEX IF NOT EXISTS idx_ioc_value ON iocs(value);

                CREATE TABLE IF NOT EXISTS mitre (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    technique_id TEXT NOT NULL,
                    technique_name TEXT,
                    tactic      TEXT,
                    alert_id    TEXT,
                    source_ip   TEXT,
                    timestamp   TEXT DEFAULT (datetime('now','utc'))
                );

                CREATE TABLE IF NOT EXISTS timeline (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_type  TEXT NOT NULL,
                    ref_id      TEXT,
                    description TEXT NOT NULL,
                    source_ip   TEXT,
                    severity    TEXT,
                    timestamp   TEXT DEFAULT (datetime('now','utc'))
                );

                CREATE TABLE IF NOT EXISTS prediction (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    source_ip   TEXT NOT NULL,
                    predicted_attack TEXT,
                    confidence  REAL,
                    context     TEXT,
                    created_at  TEXT DEFAULT (datetime('now','utc'))
                );

                CREATE TABLE IF NOT EXISTS investigation (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    incident_id TEXT NOT NULL,
                    status      TEXT DEFAULT 'open',
                    source_ip   TEXT,
                    severity    TEXT DEFAULT 'medium',
                    assigned_analyst TEXT DEFAULT 'unassigned',
                    summary     TEXT,
                    evidence    TEXT,
                    analyst_report TEXT,
                    created_at  TEXT DEFAULT (datetime('now','utc')),
                    updated_at  TEXT DEFAULT (datetime('now','utc'))
                );

                CREATE TABLE IF NOT EXISTS incidents (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    incident_id TEXT UNIQUE NOT NULL,
                    source_ip   TEXT,
                    severity    TEXT,
                    risk_score  REAL,
                    sources     TEXT,
                    alert_count INTEGER,
                    status      TEXT DEFAULT 'new',
                    payload     TEXT,
                    created_at  TEXT DEFAULT (datetime('now','utc'))
                );

                CREATE TABLE IF NOT EXISTS assets (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    ip_address  TEXT UNIQUE NOT NULL,
                    hostname    TEXT,
                    criticality TEXT DEFAULT 'medium',
                    owner       TEXT,
                    last_seen   TEXT DEFAULT (datetime('now','utc'))
                );

                CREATE TABLE IF NOT EXISTS users (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    username    TEXT UNIQUE NOT NULL,
                    role        TEXT DEFAULT 'analyst',
                    last_login  TEXT
                );
            """)
            conn.commit()
        finally:
            conn.close()

    # ── Write: Raw Events ──────────────────────────────────────────────────────

    def store_event(self, raw_event: dict, source: str = "unknown") -> bool:
        """
        Persist a raw inbound event. Deduplicates by content hash.
        source: 'suricata' | 'wazuh' | 'generic'
        """
        try:
            event_hash = hashlib.sha256(
                json.dumps(raw_event, sort_keys=True, default=str).encode()
            ).hexdigest()[:32]

            event_type = raw_event.get("event_type") or raw_event.get("type") or "unknown"
            src_ip = (
                raw_event.get("src_ip")
                or raw_event.get("source", {}).get("ip")
                or raw_event.get("agent", {}).get("ip")
            )
            dest_ip = (
                raw_event.get("dest_ip")
                or raw_event.get("destination", {}).get("ip")
            )
            severity = (
                raw_event.get("alert", {}).get("severity")
                or raw_event.get("rule", {}).get("level")
                or raw_event.get("severity")
            )
            timestamp = (
                raw_event.get("timestamp")
                or raw_event.get("@timestamp")
                or datetime.now(timezone.utc).isoformat()
            )

            conn = self._connect()
            try:
                conn.execute(
                    """
                    INSERT OR IGNORE INTO raw_events
                        (event_hash, source, event_type, src_ip, dest_ip,
                         severity, timestamp, payload)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        event_hash, source, event_type,
                        str(src_ip) if src_ip else None,
                        str(dest_ip) if dest_ip else None,
                        str(severity) if severity else None,
                        str(timestamp),
                        json.dumps(raw_event, default=str),
                    )
                )
                conn.commit()
                return True
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] store_event failed: %s", e)
            return False

    # ── Write: Alerts ──────────────────────────────────────────────────────────

    def store_alert(self, alert: dict, source_type: str = "suricata") -> bool:
        """
        Persist a Threat Engine alert. Deduplicates by alert_id.
        Also extracts IOCs from the alert.
        """
        try:
            alert_id = alert.get("alert_id") or f"alert-{id(alert)}"
            mitre_data = json.dumps(alert.get("mitre_enrichment", []), default=str)
            suppressed = 1 if alert.get("_suppressed") else 0

            conn = self._connect()
            try:
                conn.execute(
                    """
                    INSERT OR IGNORE INTO alerts
                        (alert_id, rule_id, rule_name, severity, risk_score,
                         source_ip, affected_host, source_type, mitre_data,
                         suppressed, payload)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        alert_id,
                        str(alert.get("rule_id", "")),
                        str(alert.get("rule_name", "")),
                        str(alert.get("severity", "informational")),
                        float(alert.get("risk_score", 0)),
                        str(alert.get("source_ip", "unknown")),
                        str(alert.get("affected_host", "")),
                        source_type,
                        mitre_data,
                        suppressed,
                        json.dumps(alert, default=str),
                    )
                )
                conn.commit()
            finally:
                conn.close()

            # Extract IOCs from alert
            self._extract_and_store_iocs(alert, alert_id)
            return True
        except Exception as e:
            logger.error("[EventStore] store_alert failed: %s", e)
            return False

    # ── IOC Extraction ─────────────────────────────────────────────────────────

    def _extract_and_store_iocs(self, alert: dict, alert_id: str):
        """Extract IOCs from alert fields and persist them."""
        import re
        iocs_to_store = []

        src_ip = alert.get("source_ip")
        if src_ip and src_ip not in ("unknown", ""):
            # Exclude private/loopback
            if not self._is_private_ip(src_ip):
                iocs_to_store.append(("ip", src_ip, src_ip, alert_id, "source_ip"))

        host = alert.get("affected_host")
        if host and host not in ("unknown", "Unknown", ""):
            iocs_to_store.append(("hostname", host, src_ip, alert_id, "affected_host"))

        # Scan attack story for additional IOCs
        story = alert.get("attack_story", "")
        if story:
            # Extract IPs from narrative text
            ip_pattern = re.compile(r'\b(?:\d{1,3}\.){3}\d{1,3}\b')
            for ip in ip_pattern.findall(story):
                if not self._is_private_ip(ip):
                    iocs_to_store.append(("ip", ip, src_ip, alert_id, "narrative"))

        if not iocs_to_store:
            return

        try:
            conn = self._connect()
            try:
                now = datetime.now(timezone.utc).isoformat()
                for ioc_type, value, s_ip, a_id, ctx in iocs_to_store:
                    conn.execute(
                        """
                        INSERT INTO iocs (ioc_type, value, source_ip, alert_id, context, last_seen)
                        VALUES (?, ?, ?, ?, ?, ?)
                        ON CONFLICT(ioc_type, value) DO UPDATE SET
                            last_seen = excluded.last_seen
                        """,
                        (ioc_type, value, s_ip, a_id, ctx, now)
                    )
                conn.commit()
            finally:
                conn.close()
        except Exception as e:
            logger.warning("[EventStore] IOC extraction error: %s", e)

    def _is_private_ip(self, ip: str) -> bool:
        """Returns True if IP is RFC1918 / loopback / link-local."""
        import ipaddress
        try:
            addr = ipaddress.ip_address(ip)
            return addr.is_private or addr.is_loopback or addr.is_link_local
        except Exception:
            return False

    # ── Read: Raw Events ───────────────────────────────────────────────────────

    def get_events(
        self,
        limit: int = 100,
        offset: int = 0,
        source: str = None,
        event_type: str = None,
        src_ip: str = None,
    ) -> List[dict]:
        """Paginated event query with optional filters."""
        try:
            clauses, params = [], []
            if source:
                clauses.append("source = ?"); params.append(source)
            if event_type:
                clauses.append("event_type = ?"); params.append(event_type)
            if src_ip:
                clauses.append("src_ip = ?"); params.append(src_ip)

            where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
            params += [limit, offset]

            conn = self._connect()
            try:
                rows = conn.execute(
                    f"""
                    SELECT id, source, event_type, src_ip, dest_ip,
                           severity, timestamp, ingested_at, payload
                    FROM raw_events
                    {where}
                    ORDER BY id DESC
                    LIMIT ? OFFSET ?
                    """,
                    params
                ).fetchall()
                result = []
                for r in rows:
                    d = dict(r)
                    try:
                        d["payload"] = json.loads(d["payload"])
                    except Exception:
                        pass
                    result.append(d)
                return result
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_events failed: %s", e)
            return []

    def get_event_count(self, source: str = None) -> int:
        try:
            where = "WHERE source = ?" if source else ""
            params = [source] if source else []
            conn = self._connect()
            try:
                return conn.execute(
                    f"SELECT COUNT(*) FROM raw_events {where}", params
                ).fetchone()[0]
            finally:
                conn.close()
        except Exception:
            return 0

    # ── Read: Alerts ───────────────────────────────────────────────────────────

    def get_alerts(
        self,
        limit: int = 100,
        offset: int = 0,
        severity: str = None,
        source_type: str = None,
        suppressed: bool = False,
    ) -> List[dict]:
        """Paginated alert query."""
        try:
            clauses = ["suppressed = ?"]
            params = [1 if suppressed else 0]

            if severity:
                clauses.append("severity = ?"); params.append(severity)
            if source_type:
                clauses.append("source_type = ?"); params.append(source_type)

            where = f"WHERE {' AND '.join(clauses)}"
            params += [limit, offset]

            conn = self._connect()
            try:
                rows = conn.execute(
                    f"""
                    SELECT id, alert_id, rule_id, rule_name, severity,
                           risk_score, source_ip, affected_host, source_type,
                           mitre_data, created_at, payload
                    FROM alerts
                    {where}
                    ORDER BY id DESC
                    LIMIT ? OFFSET ?
                    """,
                    params
                ).fetchall()
                result = []
                for r in rows:
                    d = dict(r)
                    try:
                        d["payload"] = json.loads(d["payload"])
                        d["mitre_data"] = json.loads(d["mitre_data"] or "[]")
                    except Exception:
                        pass
                    result.append(d)
                return result
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_alerts failed: %s", e)
            return []

    def get_alert_count(self, severity: str = None) -> int:
        try:
            where = "WHERE severity = ? AND suppressed = 0" if severity else "WHERE suppressed = 0"
            params = [severity] if severity else []
            conn = self._connect()
            try:
                return conn.execute(
                    f"SELECT COUNT(*) FROM alerts {where}", params
                ).fetchone()[0]
            finally:
                conn.close()
        except Exception:
            return 0

    # ── Read: Timeline ─────────────────────────────────────────────────────────

    def get_timeline(self, limit: int = 200) -> List[dict]:
        """Returns chronological event timeline from the dedicated timeline table."""
        try:
            conn = self._connect()
            try:
                rows = conn.execute(
                    """
                    SELECT id, event_type, ref_id, description, source_ip, severity, timestamp
                    FROM timeline
                    ORDER BY timestamp DESC, id DESC LIMIT ?
                    """,
                    (limit,)
                ).fetchall()
                return [dict(r) for r in rows]
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_timeline failed: %s", e)
            return []

    # ── Read: Metrics / KPIs ───────────────────────────────────────────────────

    def get_metrics(self) -> dict:
        """Dashboard KPI summary."""
        try:
            conn = self._connect()
            try:
                total_events    = conn.execute("SELECT COUNT(*) FROM raw_events").fetchone()[0]
                total_alerts    = conn.execute("SELECT COUNT(*) FROM alerts WHERE suppressed=0").fetchone()[0]
                critical_alerts = conn.execute("SELECT COUNT(*) FROM alerts WHERE severity='critical' AND suppressed=0").fetchone()[0]
                high_alerts     = conn.execute("SELECT COUNT(*) FROM alerts WHERE severity='high' AND suppressed=0").fetchone()[0]
                med_alerts      = conn.execute("SELECT COUNT(*) FROM alerts WHERE severity='medium' AND suppressed=0").fetchone()[0]
                suricata_events = conn.execute("SELECT COUNT(*) FROM raw_events WHERE source='suricata'").fetchone()[0]
                wazuh_events    = conn.execute("SELECT COUNT(*) FROM raw_events WHERE source='wazuh'").fetchone()[0]
                unique_attackers= conn.execute("SELECT COUNT(DISTINCT source_ip) FROM alerts WHERE suppressed=0").fetchone()[0]
                avg_risk        = conn.execute("SELECT AVG(risk_score) FROM alerts WHERE suppressed=0").fetchone()[0] or 0
                ioc_count       = conn.execute("SELECT COUNT(*) FROM iocs").fetchone()[0]

                # Events per source type breakdown
                source_breakdown = conn.execute(
                    "SELECT source, COUNT(*) as cnt FROM raw_events GROUP BY source"
                ).fetchall()

                # Severity breakdown
                sev_breakdown = conn.execute(
                    "SELECT severity, COUNT(*) as cnt FROM alerts WHERE suppressed=0 GROUP BY severity"
                ).fetchall()

                # Top event types
                top_types = conn.execute(
                    "SELECT event_type, COUNT(*) as cnt FROM raw_events GROUP BY event_type ORDER BY cnt DESC LIMIT 10"
                ).fetchall()

                return {
                    "total_events":     total_events,
                    "total_alerts":     total_alerts,
                    "critical_alerts":  critical_alerts,
                    "high_alerts":      high_alerts,
                    "medium_alerts":    med_alerts,
                    "suricata_events":  suricata_events,
                    "wazuh_events":     wazuh_events,
                    "unique_attackers": unique_attackers,
                    "avg_risk_score":   round(avg_risk, 1),
                    "ioc_count":        ioc_count,
                    "source_breakdown": {r[0]: r[1] for r in source_breakdown},
                    "severity_breakdown": {r[0]: r[1] for r in sev_breakdown},
                    "top_event_types":  [{"type": r[0], "count": r[1]} for r in top_types],
                }
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_metrics failed: %s", e)
            return {}

    # ── Read: IOCs ─────────────────────────────────────────────────────────────

    def get_iocs(self, ioc_type: str = None, limit: int = 100) -> List[dict]:
        try:
            where = "WHERE ioc_type = ?" if ioc_type else ""
            params = [ioc_type] if ioc_type else []
            params.append(limit)
            conn = self._connect()
            try:
                rows = conn.execute(
                    f"""
                    SELECT ioc_type, value, source_ip, alert_id,
                           context, first_seen, last_seen
                    FROM iocs {where}
                    ORDER BY last_seen DESC LIMIT ?
                    """,
                    params
                ).fetchall()
                return [dict(r) for r in rows]
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_iocs failed: %s", e)
            return []

    # ── Read: Top Attackers ────────────────────────────────────────────────────

    def get_top_attackers(self, limit: int = 20) -> List[dict]:
        try:
            conn = self._connect()
            try:
                rows = conn.execute(
                    """
                    SELECT source_ip,
                           COUNT(*) as alert_count,
                           MAX(risk_score) as max_risk,
                           MAX(created_at) as last_seen,
                           GROUP_CONCAT(DISTINCT severity) as severities
                    FROM alerts
                    WHERE suppressed=0 AND source_ip != 'unknown'
                    GROUP BY source_ip
                    ORDER BY alert_count DESC, max_risk DESC
                    LIMIT ?
                    """,
                    (limit,)
                ).fetchall()
                return [dict(r) for r in rows]
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_top_attackers failed: %s", e)
            return []

    # ── Read: Top Targets ──────────────────────────────────────────────────────

    def get_top_targets(self, limit: int = 20) -> List[dict]:
        try:
            conn = self._connect()
            try:
                rows = conn.execute(
                    """
                    SELECT dest_ip as target_ip,
                           COUNT(*) as event_count,
                           GROUP_CONCAT(DISTINCT event_type) as event_types
                    FROM raw_events
                    WHERE dest_ip IS NOT NULL AND dest_ip != 'unknown' AND dest_ip != ''
                    GROUP BY dest_ip
                    ORDER BY event_count DESC
                    LIMIT ?
                    """,
                    (limit,)
                ).fetchall()
                return [dict(r) for r in rows]
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_top_targets failed: %s", e)
            return []

    # ── Read: Search ───────────────────────────────────────────────────────────

    def search_events(self, query: str, limit: int = 100) -> List[dict]:
        try:
            conn = self._connect()
            try:
                # Basic LIKE search on payload for simplicity
                rows = conn.execute(
                    """
                    SELECT * FROM raw_events
                    WHERE payload LIKE ?
                    ORDER BY id DESC
                    LIMIT ?
                    """,
                    (f"%{query}%", limit)
                ).fetchall()
                
                result = []
                for r in rows:
                    d = dict(r)
                    try:
                        d["payload"] = json.loads(d["payload"])
                    except Exception: pass
                    result.append(d)
                return result
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] search_events failed: %s", e)
            return []

    # ── Read: MITRE Heatmap ────────────────────────────────────────────────────

    def get_mitre_hits(self) -> List[dict]:
        """Returns MITRE technique hit counts from stored alerts."""
        try:
            conn = self._connect()
            try:
                rows = conn.execute(
                    "SELECT mitre_data FROM alerts WHERE suppressed=0 AND mitre_data IS NOT NULL"
                ).fetchall()
            finally:
                conn.close()

            counts: Dict[str, int] = {}
            for row in rows:
                try:
                    items = json.loads(row["mitre_data"])
                    for item in items:
                        tid = item.get("id") or item.get("technique_id") or "Unknown"
                        counts[tid] = counts.get(tid, 0) + 1
                except Exception:
                    pass

            return [{"technique": k, "count": v}
                    for k, v in sorted(counts.items(), key=lambda x: -x[1])]
        except Exception as e:
            logger.error("[EventStore] get_mitre_hits failed: %s", e)
            return []


    # ── Timeline Writes ────────────────────────────────────────────────────────
    
    def store_timeline_event(self, event_type: str, ref_id: str, description: str, source_ip: str = None, severity: str = None):
        try:
            conn = self._connect()
            conn.execute(
                "INSERT INTO timeline (event_type, ref_id, description, source_ip, severity) VALUES (?, ?, ?, ?, ?)",
                (event_type, ref_id, description, source_ip, severity)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error("[EventStore] store_timeline_event failed: %s", e)

    # ── Mitre Writes & Reads ───────────────────────────────────────────────────

    def store_mitre(self, technique_id: str, technique_name: str, tactic: str, alert_id: str, source_ip: str):
        try:
            conn = self._connect()
            conn.execute(
                "INSERT INTO mitre (technique_id, technique_name, tactic, alert_id, source_ip) VALUES (?, ?, ?, ?, ?)",
                (technique_id, technique_name, tactic, alert_id, source_ip)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error("[EventStore] store_mitre failed: %s", e)

    # ── Incident Writes & Reads ────────────────────────────────────────────────

    def store_incident(self, incident: dict):
        try:
            conn = self._connect()
            conn.execute(
                """
                INSERT INTO incidents (incident_id, source_ip, severity, risk_score, sources, alert_count, status, payload)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(incident_id) DO UPDATE SET
                    alert_count = excluded.alert_count,
                    risk_score = excluded.risk_score,
                    severity = excluded.severity,
                    sources = excluded.sources,
                    payload = excluded.payload
                """,
                (
                    incident.get("incident_id") or f"inc-{incident.get('source_ip')}-{int(time.time())}",
                    incident.get("source_ip"),
                    incident.get("severity", "medium"),
                    float(incident.get("risk_score", 0)),
                    json.dumps(incident.get("sources", [])),
                    int(incident.get("alert_count", 0)),
                    incident.get("status", "new"),
                    json.dumps(incident)
                )
            )
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error("[EventStore] store_incident failed: %s", e)

    def get_incidents(self, limit: int = 100, offset: int = 0) -> List[dict]:
        try:
            conn = self._connect()
            rows = conn.execute("SELECT * FROM incidents ORDER BY id DESC LIMIT ? OFFSET ?", (limit, offset)).fetchall()
            conn.close()
            res = []
            for r in rows:
                d = dict(r)
                if d.get("payload"):
                    d["payload"] = json.loads(d["payload"])
                if d.get("sources"):
                    d["sources"] = json.loads(d["sources"])
                res.append(d)
            return res
        except Exception as e:
            logger.error("[EventStore] get_incidents failed: %s", e)
            return []

    # ── Investigation Writes & Reads ───────────────────────────────────────────

    def store_investigation(self, incident_id: str, summary: str, evidence: str, analyst_report: str = "", source_ip: str = "unknown", severity: str = "medium", assigned_analyst: str = "unassigned"):
        try:
            conn = self._connect()
            conn.execute(
                """
                INSERT INTO investigation (incident_id, summary, evidence, analyst_report, source_ip, severity, assigned_analyst)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (incident_id, summary, evidence, analyst_report, source_ip, severity, assigned_analyst)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error("[EventStore] store_investigation failed: %s", e)

    def get_investigations(self, limit: int = 100) -> List[dict]:
        try:
            conn = self._connect()
            rows = conn.execute("SELECT * FROM investigation ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
            conn.close()
            return [dict(r) for r in rows]
        except Exception as e:
            logger.error("[EventStore] get_investigations failed: %s", e)
            return []

    # ── Prediction Writes & Reads ──────────────────────────────────────────────

    def store_prediction(self, source_ip: str, predicted_attack: str, confidence: float, context: str):
        try:
            conn = self._connect()
            conn.execute(
                """
                INSERT INTO prediction (source_ip, predicted_attack, confidence, context)
                VALUES (?, ?, ?, ?)
                """,
                (source_ip, predicted_attack, confidence, context)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error("[EventStore] store_prediction failed: %s", e)

    def get_predictions(self, limit: int = 100) -> List[dict]:
        try:
            conn = self._connect()
            rows = conn.execute("SELECT * FROM prediction ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
            conn.close()
            return [dict(r) for r in rows]
        except Exception as e:
            logger.error("[EventStore] get_predictions failed: %s", e)
            return []

    # ── Asset Writes & Reads ───────────────────────────────────────────────────

    def store_asset(self, ip_address: str, hostname: str = None):
        if self._is_private_ip(ip_address) or ip_address in ("127.0.0.1", "0.0.0.0", "unknown", ""):
            return
        try:
            conn = self._connect()
            conn.execute(
                """
                INSERT INTO assets (ip_address, hostname) VALUES (?, ?)
                ON CONFLICT(ip_address) DO UPDATE SET
                    last_seen = datetime('now','utc')
                """,
                (ip_address, hostname)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error("[EventStore] store_asset failed: %s", e)

    def get_assets(self, limit: int = 100) -> List[dict]:
        try:
            conn = self._connect()
            rows = conn.execute("SELECT * FROM assets ORDER BY last_seen DESC LIMIT ?", (limit,)).fetchall()
            conn.close()
            return [dict(r) for r in rows]
        except Exception as e:
            logger.error("[EventStore] get_assets failed: %s", e)
            return []

    # ── User Writes & Reads ────────────────────────────────────────────────────

    def get_users(self, limit: int = 100) -> List[dict]:
        try:
            conn = self._connect()
            rows = conn.execute("SELECT * FROM users ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
            conn.close()
            return [dict(r) for r in rows]
        except Exception as e:
            logger.error("[EventStore] get_users failed: %s", e)
            return []

    def store_user(self, username: str, role: str = 'analyst'):
        try:
            conn = self._connect()
            conn.execute(
                "INSERT INTO users (username, role) VALUES (?, ?) ON CONFLICT(username) DO NOTHING",
                (username, role)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error("[EventStore] store_user failed: %s", e)

    # ── WebSocket Feed Queries ─────────────────────────────────────────────────

    def get_max_event_id(self) -> int:
        try:
            conn = self._connect()
            try:
                row = conn.execute("SELECT MAX(id) FROM raw_events").fetchone()
                return row[0] if row and row[0] else 0
            finally:
                conn.close()
        except Exception:
            return 0

    def get_max_alert_id(self) -> int:
        try:
            conn = self._connect()
            try:
                row = conn.execute("SELECT MAX(id) FROM alerts").fetchone()
                return row[0] if row and row[0] else 0
            finally:
                conn.close()
        except Exception:
            return 0

    def get_events_since(self, since_id: int, limit: int = 50) -> List[dict]:
        try:
            conn = self._connect()
            try:
                rows = conn.execute(
                    "SELECT * FROM raw_events WHERE id > ? ORDER BY id ASC LIMIT ?",
                    (since_id, limit)
                ).fetchall()
                res = []
                for r in rows:
                    d = dict(r)
                    if d.get("payload"):
                        try:
                            d["payload"] = json.loads(d["payload"])
                        except Exception: pass
                    res.append(d)
                return res
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_events_since failed: %s", e)
            return []

    def get_alerts_since(self, since_id: int, limit: int = 20) -> List[dict]:
        try:
            conn = self._connect()
            try:
                rows = conn.execute(
                    "SELECT * FROM alerts WHERE id > ? ORDER BY id ASC LIMIT ?",
                    (since_id, limit)
                ).fetchall()
                res = []
                for r in rows:
                    d = dict(r)
                    if d.get("payload"):
                        try:
                            d["payload"] = json.loads(d["payload"])
                        except Exception: pass
                    res.append(d)
                return res
            finally:
                conn.close()
        except Exception as e:
            logger.error("[EventStore] get_alerts_since failed: %s", e)
            return []
